### ISSUE TITLE
Popup size way too small

### ISSUE THREAD

**Issue by alexcoder04** [Redstonerayy/yt-looper#3]
![scr](https://user-images.githubusercontent.com/70093931/232843937-7812e006-064f-448d-94a2-2e182df36515.png)

Firefox 112.0 (64 bit)
Artix Linux build

**Comment by Redstonerayy** [comment]
fixed in version 1.0.1 76990cf95ceffb41317190883464d67fcced4e05, may take some time to roll out from firefox store
